from enum import StrEnum

class ArtifactType(StrEnum):
    SOURCE_POINT_CLOUD="SOURCE_POINT_CLOUD"; CANONICAL_POINT_CLOUD="CANONICAL_POINT_CLOUD"
    SEGMENTATION_RESULT="SEGMENTATION_RESULT"; GEOMETRY_MODEL="GEOMETRY_MODEL"
    IFC_MODEL_UNVALIDATED="IFC_MODEL_UNVALIDATED"; IFC_MODEL="IFC_MODEL"; VALIDATION_REPORT="VALIDATION_REPORT"
class ChecksumAlgorithm(StrEnum): SHA256="SHA256"
class WorkflowStatus(StrEnum):
    STARTED="STARTED"; IN_PROGRESS="IN_PROGRESS"; CANCELLATION_REQUESTED="CANCELLATION_REQUESTED"; COMPLETED="COMPLETED"; FAILED="FAILED"; CANCELLED="CANCELLED"
class WorkflowInitiationStatus(StrEnum): START_REQUESTED="START_REQUESTED"; START_ACCEPTED="START_ACCEPTED"; START_FAILED="START_FAILED"
class WorkflowStage(StrEnum): SEGMENTATION="SEGMENTATION"; GEOMETRY_EXTRACTION="GEOMETRY_EXTRACTION"; IFC_GENERATION="IFC_GENERATION"; IFC_VALIDATION="IFC_VALIDATION"; ARTIFACT_PREPARATION="ARTIFACT_PREPARATION"; COMPLETED="COMPLETED"
class StageStatus(StrEnum): PENDING="PENDING"; IN_PROGRESS="IN_PROGRESS"; RETRY_SCHEDULED="RETRY_SCHEDULED"; COMPLETED="COMPLETED"; FAILED="FAILED"; CANCELLED="CANCELLED"; TIMED_OUT="TIMED_OUT"
class ValidationStatus(StrEnum): PASSED="PASSED"; PASSED_WITH_WARNINGS="PASSED_WITH_WARNINGS"; FAILED="FAILED"
class CommandType(StrEnum): START_SEGMENTATION="StartSegmentation"; GENERATE_GEOMETRY="GenerateGeometry"; GENERATE_IFC="GenerateIFC"; VALIDATE_IFC="ValidateIFC"; PREPARE_ARTIFACT_DELIVERY="PrepareArtifactDelivery"
class SubjectType(StrEnum): PROJECT="Project"; SITE="Site"; INGESTION_REQUEST="IngestionRequest"; POINT_CLOUD_FILE="PointCloudFile"; CANONICAL_POINT_CLOUD="CanonicalPointCloud"; WORKFLOW="Workflow"; SEGMENTATION_RESULT="SegmentationResult"; GEOMETRY_MODEL="GeometryModel"; IFC_MODEL="IFCModel"; ARTIFACT="Artifact"
class SourceChannel(StrEnum): UPLOAD_PORTAL="UPLOAD_PORTAL"; EXTERNAL_PORTAL="EXTERNAL_PORTAL"; REST_API="REST_API"; WEBHOOK="WEBHOOK"; BULK_UPLOAD="BULK_UPLOAD"; AUTOMATED_SOURCE="AUTOMATED_SOURCE"
class IngestionStatus(StrEnum): CREATED="CREATED"; AWAITING_UPLOAD="AWAITING_UPLOAD"; UPLOAD_RECEIVED="UPLOAD_RECEIVED"; VALIDATING="VALIDATING"; VALIDATION_FAILED="VALIDATION_FAILED"; CANONICALIZING="CANONICALIZING"; CANONICALIZATION_FAILED="CANONICALIZATION_FAILED"; READY_FOR_WORKFLOW="READY_FOR_WORKFLOW"; WORKFLOW_STARTED="WORKFLOW_STARTED"; FAILED="FAILED"
